export const TASK_ICONS: Record<string, string> = {
  "depth-estimation": "🗺️",
  "image-classification": "🏷️",
  "image-feature-extraction": "🧬",
  "image-segmentation": "✂️",
  "image-to-image": "🔄",
  "image-to-text": "📝",
  "image-to-video": "🎬",
  "keypoint-detection": "📍",
  "mask-generation": "🎭",
  "object-detection": "🔎",
  "video-classification": "🎞️",
  "text-to-image": "🎨",
  "text-to-video": "📹",
  "unconditional-image-generation": "✨",
  "video-to-video": "🔁",
  "zero-shot-image-classification": "🧩",
  "zero-shot-object-detection": "🎯",
  "text-to-3d": "🧊",
  "image-to-3d": "🗿",
};
